pipeline {
    agent any

    triggers {
        pollSCM('H/5 * * * *')
    }

    environment {
        COMPOSE_CMD = "docker compose"
    }

    stages {

        stage('Build') {
            steps {
                echo "Build con Docker Compose (CI)"
                sh '''
                ls -la
                ls -la .env.ci || echo ".env.ci NON TROVATO"
                docker compose --env-file .env.ci build sentiment-api
                '''
            }
        }

        stage('Test') {
            steps {
                echo "Esecuzione test nel container sentiment-api"
                sh '''
                docker compose --env-file .env.ci run --rm sentiment-api python -m pytest tests/ -v
                '''
            }
        }
        

        stage('Deploy') {
            steps {
                echo "Deploy con Docker Compose"
                sh "docker compose --env-file .env.ci up -d sentiment-api"
            }
        }
    }

    post {
        success {
            echo 'Pipeline completata con successo'
        }
        failure {
            echo 'Pipeline fallita'
        }
    }
}
