pipeline {
    agent any

    options {
        // Evita il checkout automatico (lo abbiamo già risolto)
        skipDefaultCheckout(true)
    }

    triggers {
        // Polling SCM ogni 5 minuti
        pollSCM('H/5 * * * *')
    }

    environment {
        COMPOSE_CMD = "docker compose"
        ENV_FILE = ".env.ci"
    }

    stages {

        stage('Build') {
            steps {
                echo "Build con Docker Compose (CI)"
                sh "${COMPOSE_CMD} --env-file ${ENV_FILE} build sentiment-api"
            }
        }

        stage('Test') {
            steps {
                echo "Esecuzione test"
                sh """
                cd api
                python -m pip install --upgrade pip
                pip install -r requirements.txt
                pip install pytest
                pytest tests/ -v
                """
            }
        }

        stage('Deploy') {
            steps {
                echo "Deploy con Docker Compose (CI)"
                sh "${COMPOSE_CMD} --env-file ${ENV_FILE} up -d sentiment-api"
            }
        }
    }

    post {
        success {
            echo 'Pipeline completata con successo'
        }
        failure {
            echo 'Pipeline fallita'
        }
    }
}
